### PR TITLE
Sqloper doc additions

### PR DESCRIPTION
**Pull request by rgraff**
Explains how the sqloper query is used to create opers, with addition info on the oper configuration options.

### CODE REVIEW

**Comment by SadieCat** [comment]
`docs/3/configuration/_oper.md` documents the core oper config, sqloper is documented in 3/modules/sqloper.md`.

**Comment by rgraff** [comment]
I made update to both files. In `docs/3/configuration/_oper.md` I added a few options for oper config that were not in the table. 

In `docs/3/modules/sqloper.md` I added some clarification to how the select rows are turned into opers. I link from sqloper to the oper config because I think it adds clarification about how the schema works.

Is there something wrong or misleading the changes proposed? Let me know so I can fix.

**Comment by SadieCat** [comment]
>I made update to both files. In docs/3/configuration/_oper.md I added a few options for oper config that were not in the table.

You added stuff from a module to the core oper config table.

**Comment by rgraff** [comment]
I'll revert the changes to the core oper config table and submit under a different PR with clarification.

**Pull request merged**
