### PR TITLE
Convert docs/3/commands/ to yaml

### PR DESCRIPTION
**Pull request by progval**
This should help with GH-107.

This does not change the HTML output, except for the removed
HTML comment (`<!-- This file contains a page fragment. Any changes will affect all pages that include it. -->`)

For the record, I used this script:

```
import glob
import pprint
import re
import textwrap

for filename in sorted(glob.glob("docs/3/commands/_*.md")):
    cmd_name = re.match("docs/3/commands/_cmd_(.*).md", filename).group(1)
    print(cmd_name)
    with open(filename) as fd:
        content = fd.read()
    m = re.match(r".*\n### `(?P<syntax>[^`]+)`\n+(?P<description>[^#]*)\n+(#### Example Usage\n+(?P<example>.*))?$", content, re.DOTALL | re.MULTILINE)
    pprint.pprint(m.groupdict())

    with open(f"docs/3/commands/_{cmd_name}.yml", "wt") as fd:
        fd.write(textwrap.dedent(
            f"""
            name: {cmd_name}
            syntax: >-
              {m.group("syntax")}
            description: |-
            """
        ).lstrip())

        fd.write(textwrap.indent(m.group("description"), "  "))

        if m.group("example"):
            fd.write("example: |-\n" + textwrap.indent(m.group("example"), "  "))
```

plus a manual edit to `_stats.yml` because the regexp could not handle the
extra subtitle, and added newlines at the end of files missing one.

### CODE REVIEW

**Comment by SadieCat** [comment]
The syntax of this differs from how the config section of modules work. Is it possible to make them the same so we can use the same code for generating the helpop?

**Comment by progval** [comment]
What are the differences? Capitalization of `name` and missing `param_count`?

**Comment by SadieCat** [comment]
The syntax field for this includes the command name and also the capitalization thing.


`param_count` isn't really necessary in this context so it can be omitted.

**Comment by SadieCat** [comment]
Can you split up the example like I did to the module examples?

**Comment by progval** [comment]
FYI the latest commit introduces the following changes:

```diff
diff site-old/3/commands/index.html site/3/commands/index.html
593c593
< <p>Specifies "hunter2" as the local server password.</p>
---
> <p>Specifies "hunter2" as the local server password:</p>
599c599
< <p>Pings the local server with the cookie "wibble".</p>
---
> <p>Pings the local server with the cookie "wibble":</p>
602c602
< <p>Pings <code>irc2.example.com</code> with the cookie "wobble".</p>
---
> <p>Pings <code>irc2.example.com</code> with the cookie "wobble":</p>
608c608
< <p>Responds to a ping from the local server with the cookie "wibble".</p>
---
> <p>Responds to a ping from the local server with the cookie "wibble":</p>
611c611
< <p>Responds to a ping from <code>irc2.example.com</code> with the cookie "wobble".</p>
---
> <p>Responds to a ping from <code>irc2.example.com</code> with the cookie "wobble":</p>
804c804
< <p>Changes the topic for #trains to "choo choo"</p>
---
> <p>Changes the topic for #trains to "choo choo":</p>
846c846
< <p>Sends "Rebooting for updates at 20:00 UTC" to all users with user mode <code>w</code> (wallops) enabled.</p>
---
> <p>Sends "Rebooting for updates at 20:00 UTC" to all users with user mode <code>w</code> (wallops) enabled:</p>
```

**Pull request merged**
